IO MACRO X,Y
   MOV AH,X
   LEA DX,Y
   INT 21H
   ENDM
DATAS SEGMENT USE16
   STR DB 'Please input:','$'
   R1 DB '  decimalism!','$'
   R2 DB '  capital letter!','$'
   R3 DB '  small letter!','$'
   CRLF DB 13,10,'$'
DATAS ENDS

STACKS SEGMENT USE16
   ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT USE16
   ASSUME CS:CODES,DS:DATAS,SS:STACKS

START:
    MOV AX,DATAS
    MOV DS,AX
    
L:  IO 09H,STR;打印提示语
    MOV AH,1
    INT 21H
    CMP AL,30H
    JB EXIT
NEXT: CMP AL,3AH
    JB OUT1
    CMP AL,41H
    JB EXIT
    CMP AL,5BH
    JB OUT2
    CMP AL,61H
    JB EXIT
    CMP AL,7BH
    JB OUT3
EXIT: IO 09H,CRLF
    MOV AH,4CH
    INT 21H

OUT1: IO 09H,R1
    IO 09H,CRLF
    JMP L
OUT2: IO 09H,R2
    IO 09H,CRLF
    JMP L
OUT3: IO 09H,R3
    IO 09H,CRLF
    JMP L
CODES ENDS
   END START
