// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue May 09 09:44:52 2017

pencode_module pencode_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.x(x_sig) ,	// input [7:0] x_sig
	.y(y_sig) ,	// output [2:0] y_sig
	.Valid(Valid_sig) 	// output  Valid_sig
);

