// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat May 13 11:30:02 2017

Digitron_NumDisplay_module Digitron_NumDisplay_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.Count_D_Display(Count_D_Display_sig) ,	// input  Count_D_Display_sig
	.Count_P_Display(Count_P_Display_sig) ,	// input  Count_P_Display_sig
	.Count_D(Count_D_sig) ,	// input [23:0] Count_D_sig
	.Count_P(Count_P_sig) ,	// input [23:0] Count_P_sig
	.Duty(Duty_sig) ,	// input [7:0] Duty_sig
	.Digitron_Out(Digitron_Out_sig) ,	// output [7:0] Digitron_Out_sig
	.DigitronCS_Out(DigitronCS_Out_sig) 	// output [5:0] DigitronCS_Out_sig
);

defparam Digitron_NumDisplay_module_inst.T100MS = 'b0000000011001000;
defparam Digitron_NumDisplay_module_inst._0 = 'b00111111;
defparam Digitron_NumDisplay_module_inst._1 = 'b00000110;
defparam Digitron_NumDisplay_module_inst._2 = 'b01011011;
defparam Digitron_NumDisplay_module_inst._3 = 'b01001111;
defparam Digitron_NumDisplay_module_inst._4 = 'b01100110;
defparam Digitron_NumDisplay_module_inst._5 = 'b01101101;
defparam Digitron_NumDisplay_module_inst._6 = 'b01111101;
defparam Digitron_NumDisplay_module_inst._7 = 'b00000111;
defparam Digitron_NumDisplay_module_inst._8 = 'b01111111;
defparam Digitron_NumDisplay_module_inst._9 = 'b01101111;
defparam Digitron_NumDisplay_module_inst._A = 'b01110111;
defparam Digitron_NumDisplay_module_inst._B = 'b01111100;
defparam Digitron_NumDisplay_module_inst._C = 'b00111001;
defparam Digitron_NumDisplay_module_inst._D = 'b01011110;
defparam Digitron_NumDisplay_module_inst._E = 'b01111001;
defparam Digitron_NumDisplay_module_inst._F = 'b01110001;
defparam Digitron_NumDisplay_module_inst._Wu = 'b01000000;
