// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat May 13 11:29:47 2017

Duty_Period_Adjust_module Duty_Period_Adjust_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.AddDuty_In(AddDuty_In_sig) ,	// input  AddDuty_In_sig
	.SubDuty_In(SubDuty_In_sig) ,	// input  SubDuty_In_sig
	.AddPeriod_In(AddPeriod_In_sig) ,	// input  AddPeriod_In_sig
	.SubPeriod_In(SubPeriod_In_sig) ,	// input  SubPeriod_In_sig
	.Duty(Duty_sig) ,	// output [7:0] Duty_sig
	.Count_P(Count_P_sig) 	// output [23:0] Count_P_sig
);

