// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Fri Apr 07 19:22:39 2017

trigger_module trigger_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Setn(Setn_sig) ,	// input  Setn_sig
	.Clrn(Clrn_sig) ,	// input  Clrn_sig
	.J(J_sig) ,	// input [4:0] J_sig
	.K(K_sig) ,	// input [4:0] K_sig
	.Q(Q_sig) ,	// output [4:0] Q_sig
	.Q_n(Q_n_sig) 	// output [4:0] Q_n_sig
);

defparam trigger_module_inst.Timex = 'b111101000010010000000;
