%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  file name:    matladhomework chapter4.m
%%%  author:       仁青尖参
%%%  version:      1.0
%%%  update time:  10/26/2019
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%定义二极管的参数
T=27;
Is=exp(-14);
%%建立显示二极管IV曲线的标体以及坐标轴
H=axes('unit','normalized','position',[0,0,1,1],'visible','off');
set(gcf,'currentaxes',H);
str='\fontname{隶书}MATLAB的二极管建模';
text(0,0.95,str,'fontsize',10);
h_fig=get(H,'parent');
set(h_fig,'unit','normalized','position',[0.1,0.2,0.7,0.4]);
h_axes=axes('parent',h_fig,...
'unit','normalized','position',[0.1,0.1,0.7,0.8],...
'xlim',[-6 0.8],'ylim',[-10 10],'fontsize',10);
%%建立二极管的输入参数界面
h_text=uicontrol(h_fig,'style','text',...
'unit','normalized','position',[0.8,0.9,0.1,0.1],...
'horizontal','left','string',{'请于右侧输入二极管参数q',});
h_edit=uicontrol(h_fig,'style','edit',...
'unit','normalized','position',[0.90,0.90,0.10,0.10],...
'horizontal','left');
h_text2=uicontrol(h_fig,'style','text',...
'unit','normalized','position',[0.8,0.8,0.1,0.1],...
'horizontal','left','string',{'请于右侧输入二极管参数k',});
h_edit2=uicontrol(h_fig,'style','edit',...
'unit','normalized','position',[0.90,0.8,0.10,0.10],...
'horizontal','left');
h_text3=uicontrol(h_fig,'style','text',...
'unit','normalized','position',[0.8,0.7,0.1,0.1],...
'horizontal','left','string',{'请于右侧输入二极管参数d',});
h_edit3=uicontrol(h_fig,'style','edit',...
'unit','normalized','position',[0.90,0.7,0.10,0.10],...
'horizontal','left');
h_text4=uicontrol(h_fig,'style','text',...
'unit','normalized','position',[0.8,0.4,0.2,0.2],...
'horizontal','left','string',{'二极管I-V关系式 id=exp(-14)*(exp(q*v*d/(27*k))-1)',});
%%画出二极管的I-V曲线
h_push1=uicontrol(h_fig,'style','push','unit','normalized','position',[0.8,0.3,0.10,0.10],'string','建立未击穿模型','callback',[...
'q=str2num(get(h_edit,''string''));'...
'k=str2num(get(h_edit2,''string''));'...
'd=str2num(get(h_edit3,''string''));'...
'A=exp(-14)*(exp(q*-5*d/(27*k))-1);'...
'v1=-6:0.01:-5;'...
'v2=-5:0.01:0.8;'...
'x=exp(14)*(v1+5)+A;'...
'x2=exp(-14)*(exp(q*v2*d/(27*k))-1);'...
'plot(v2,x2);'])
h_push2=uicontrol(h_fig,'style','push','unit','normalized','position',[0.9,0.3,0.10,0.10],'string','建立击穿模型','callback',[...
'q=str2num(get(h_edit,''string''));'...
'k=str2num(get(h_edit2,''string''));'...
'd=str2num(get(h_edit3,''string''));'...
'A=exp(-14)*(exp(q*-5*d/(27*k))-1);'...
'v1=-6:0.01:-5;'...
'x=exp(14)*(v1+5)+A;'...
'plot(v1,x);'])