// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Mon May 08 18:43:25 2017

decode_module decode_module_inst
(
	.a2(a2_sig) ,	// input  a2_sig
	.a1(a1_sig) ,	// input  a1_sig
	.a0(a0_sig) ,	// input  a0_sig
	.y7(y7_sig) ,	// output  y7_sig
	.y6(y6_sig) ,	// output  y6_sig
	.y5(y5_sig) ,	// output  y5_sig
	.y4(y4_sig) ,	// output  y4_sig
	.y3(y3_sig) ,	// output  y3_sig
	.y2(y2_sig) ,	// output  y2_sig
	.y1(y1_sig) ,	// output  y1_sig
	.y0(y0_sig) 	// output  y0_sig
);

