// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed Apr 19 15:46:59 2017

choose_wave_module choose_wave_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.SW_Sin_In(SW_Sin_In_sig) ,	// input  SW_Sin_In_sig
	.SW_Square_In(SW_Square_In_sig) ,	// input  SW_Square_In_sig
	.SW_Sawtooth_In(SW_Sawtooth_In_sig) ,	// input  SW_Sawtooth_In_sig
	.KW_In(KW_In_sig) ,	// input [11:0] KW_In_sig
	.Wave_Data(Wave_Data_sig) 	// output [7:0] Wave_Data_sig
);

