// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed Apr 19 15:47:04 2017

dac_module dac_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Wave_Data(Wave_Data_sig) ,	// input [7:0] Wave_Data_sig
	.DA_CLK(DA_CLK_sig) ,	// output  DA_CLK_sig
	.DA_Data_Out(DA_Data_Out_sig) 	// output [7:0] DA_Data_Out_sig
);

