// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Sat Apr 08 11:01:06 2017

Accumulator_module Accumulator_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.Result(Result_sig) 	// output [7:0] Result_sig
);

defparam Accumulator_module_inst.T05S = 'b10110111000110110000000;
