// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun May 07 21:59:03 2017

Adder_module Adder_module_inst
(
	.a(a_sig) ,	// input  a_sig
	.b(b_sig) ,	// input  b_sig
	.c_in(c_in_sig) ,	// input  c_in_sig
	.s(s_sig) ,	// output  s_sig
	.c_out(c_out_sig) 	// output  c_out_sig
);

