// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed May 10 14:52:56 2017

triggerD2 triggerD2_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Setn(Setn_sig) ,	// input  Setn_sig
	.Clrn(Clrn_sig) ,	// input  Clrn_sig
	.Sw_In(Sw_In_sig) ,	// input [7:0] Sw_In_sig
	.LED_Out(LED_Out_sig) 	// output [7:0] LED_Out_sig
);

