.386
IO MACRO X,Y
   MOV AH,X
   LEA DX,Y
   INT 21H
   ENDM
DATAS SEGMENT USE16
   PROMPT1 DB 'the signed decimal number is: ','$'
   PROMPT2 DB 'the unsigned decimal number is: ','$'
   PROMPT3 DB 'the unsigned hexadecimal number is: ','$'
   PROMPT4 DB 'the signed hexadecimal number is: ','$'
   DA DD -0A62B89F0H,-739066ABH,11112222H,88889999H
   LEN DW ($-DA)/4
   STR1 DB 20 DUP(0) 
   TEN DD 10
   SIXTEEN DD 16
   CRLF DB 13,10,'$'
DATAS ENDS

STACKS SEGMENT USE16
   ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT USE16
   ASSUME CS:CODES,DS:DATAS,SS:STACKS

START:
    MOV AX,DATAS
    MOV DS,AX
    LEA BX,DA
    MOV CX,LEN

P:  IO 09H,PROMPT1
    MOV EAX,[BX]
    CALL DISPTENUNSIGN
    IO 09H,CRLF

    IO 09H,PROMPT2
    MOV EAX,[BX]
    CALL DISPTENSIGN
    IO 09H,CRLF

    IO 09H,PROMPT3
    MOV EAX,[BX]
    CALL DISPHEXUNSIGN
    IO 09H,CRLF

    IO 09H,PROMPT4
    MOV EAX,[BX]
    CALL DISPHEXSIGN
    IO 09H,CRLF
    IO 09H,CRLF

    ADD EBX,4

    LOOP P


    MOV AH,4CH
    INT 21H

DISPTENSIGN PROC NEAR;显示10进制有符号程序，入口为EAX
   PUSHAD
   MOV DI,0
   MOV CX,0
   OR EAX,EAX
   JNS L1
   MOV STR1[DI],'-'
   INC DI
   NEG EAX
L1:  XOR EDX,EDX
   DIV TEN
   PUSH DX
   INC CX
   CMP EAX,0
   JNZ L1
L2: POP AX
   ADD AL,30H
   MOV STR1[DI],AL
   INC DI
   LOOP L2
   MOV STR1[DI],'D'
   MOV STR1[DI+1],'$'
   IO 09H,STR1
   POPAD
   RET
DISPTENSIGN ENDP

DISPTENUNSIGN PROC NEAR;显示10进制无符号程序，入口为EAX
   PUSHAD
   MOV DI,0
   MOV CX,0
L3:  XOR EDX,EDX
   DIV TEN
   PUSH DX
   INC CX
   CMP EAX,0
   JNZ L3
L4: POP AX
   ADD AL,30H
   MOV STR1[DI],AL
   INC DI
   LOOP L4
   MOV STR1[DI],'D'
   MOV STR1[DI+1],'$'
   IO 09H,STR1
   POPAD
   RET
DISPTENUNSIGN ENDP

DISPHEXSIGN PROC NEAR
   PUSHAD
   MOV DI,0
   MOV CX,0
   OR EAX,EAX
   JNS L5
   MOV STR1[DI],'-'
   INC DI
   NEG EAX
L5:  XOR EDX,EDX
   DIV SIXTEEN
   PUSH DX
   INC CX
   CMP EAX,0
   JNZ L5
L6: POP AX
   CMP AL,9H
   JNA NEXT1
   ADD AL,7
NEXT1:   ADD AL,30H
   MOV STR1[DI],AL
   INC DI
   LOOP L6
   MOV STR1[DI],'H'
   MOV STR1[DI+1],'$'
   IO 09H,STR1
   POPAD
   RET
DISPHEXSIGN ENDP

DISPHEXUNSIGN PROC NEAR
   PUSHAD
   MOV DI,0
   MOV CX,0
L7:  XOR EDX,EDX
   DIV SIXTEEN
   PUSH DX
   INC CX
   CMP EAX,0
   JNZ L7
L8: POP AX
   CMP AL,9H
   JNA NEXT2
   ADD AL,7
NEXT2:   ADD AL,30H
   MOV STR1[DI],AL
   INC DI
   LOOP L8
   MOV STR1[DI],'H'
   MOV STR1[DI+1],'$'
   IO 09H,STR1
   POPAD
   RET
DISPHEXUNSIGN ENDP

CODES ENDS
   END START
