.386
PRST MACRO X
    PUSH DX
    PUSH AX
    LEA DX,X
    MOV AH,9
    INT 21H
    POP AX
    POP DX
ENDM

PRC MACRO X
    PUSH DX
    PUSH AX
    MOV DL,X
    MOV AH,2
    INT 21H
    POP AX
    POP DX
ENDM

SCAN MACRO X
    PUSH DX
    PUSH AX
    LEA DX,X
    MOV AH,0AH
    INT 21H
    POP AX
    POP DX
ENDM

DATAS SEGMENT USE16
   COUNT = 40
          ;'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
   MLAB DB '56789ABCDEFGHIJKLMNOPQRSTUVWXYZ01234'
   JLAB DB 'VWXYZ0123456789ABCDEFGHIJKLMNOPQRSTU'
   CRLF DB 13,10,'$'
   PROMPT1 DB 'Please set password:',13,10,'$'
   PROMPT2 DB 'Please input password: ',13,10,'$'
   PROMPT3 DB 'Login failed! The password is:',13,10,'$'
   PROMPT4 DB 'Login succeed! The password is:',13,10,'$'
   STR1 DB 40 DUP(0)
   MCODE DB 40 DUP(0)
   JCODE DB 40 DUP(0)
   LEN1 DW 0
   LEN2 DW 0
DATAS ENDS

STACKS SEGMENT USE16
   ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT USE16
   ASSUME CS:CODES,DS:DATAS,SS:STACKS

START:
    MOV AX,DATAS
    MOV DS,AX

    CALL MP
    CALL LP

    MOV AH,4CH
    INT 21H

MP PROC NEAR
    PUSHA
    PRST PROMPT1
    MOV CX,COUNT
    LEA SI,MCODE
FOR1:XOR AX,AX
    MOV AH,7H
    INT 21H
    MOV AH,0
    CMP AL,13
    JE EXIT1
    CMP AL,10
    JE EXIT1
    SUB AL,'0'
    CMP AL,0AH
    JB NEXT1
    SUB AL,7H
    CMP AL,24H
    JB NEXT1
    SUB AL,20H
NEXT1: MOV DI,AX
      MOV AL,MLAB[DI]
      MOV [SI],AX
      INC SI
      INC LEN1
      MOV DL,'*'
      MOV AH,2
      INT 21H
      LOOP FOR1
EXIT1: PRST CRLF
      POPA
      RET
MP ENDP

LP PROC NEAR
    PUSHA
    PRST PROMPT2
    MOV CX,COUNT
    LEA SI,STR1
FOR2:XOR AX,AX
    MOV AH,7H
    INT 21H
    MOV AH,0
    CMP AL,13
    JE EXIT2
    CMP AL,10
    JE EXIT2
    SUB AL,'0'
    CMP AL,0AH
    JB NEXT2
    SUB AL,7H
    CMP AL,24H
    JB NEXT2
    SUB AL,20H
NEXT2: MOV DI,AX
      MOV AL,MLAB[DI]
      MOV [SI],AX
      INC SI
      INC LEN2
      MOV DL,'*'
      MOV AH,2
      INT 21H
      LOOP FOR2
EXIT2: PRST CRLF
      MOV AX,LEN1
      CMP AX,LEN2
      JNE FAIL
      MOV AX,SEG MCODE
      MOV ES,AX
      LEA SI,STR1
      LEA DI,MCODE
      MOV CX,LEN1
      CLD
      REPZ CMPSB
      JNE FAIL
SUCE: PRST PROMPT4
      JMP OUT1
FAIL: PRST PROMPT3
OUT1:  CALL OUTPASS   
      POPA
      RET
LP ENDP

OUTPASS PROC NEAR
    PUSHA
    MOV CX,LEN1
    LEA SI,JCODE
    LEA DI,MCODE
FOR3: XOR AX,AX
    MOV AL,[DI]
    MOV AH,0
    SUB AL,'0'
    CMP AL,0AH
    JB NEXT3
    SUB AL,7H
NEXT3: MOV BX,AX
    MOV AL,JLAB[BX]
    MOV [SI],AL
    INC SI
    INC DI
    LOOP FOR3
    MOV [SI],'$'
    PRST JCODE
    PRST CRLF
    POPA
    RET
OUTPASS ENDP

CODES ENDS
   END START
