#+TITLE: 概率论与数理统计公式
#+AUTHOR: liaojunxuan at whu dot edu dot cn
#+DATE: <2021-12-24 Fri>

# This work is licensed under a [[https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh][Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License]].


* 公式
:PROPERTIES:
:ANKI_DECK: 概率论与数理统计
:END:
** 概率公式 :计算概率:
*** 概率的基本性质
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
概率的基本性质
**** Back
+ 不可能事件的概率为 0
+ 有限可加性
+ 可减性、单调性
  若$B\subset A$ ，则 $P(A-B)=P(A)-P(B)$ ，且$P(B)\leqslant P(A)$.
+ 逆事件概率公式
  $P(\overline{A})=1-P(A)$.
*** 加法公式
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
加法公式
**** Back
1. 设$A$ ，$B$ 是两事件，则$P(A\cup B) = P(A)+P(B)-P(AB)$.
2. 设$A_1, A_2, \cdots, A_n(n\geqslant 2)$ 是$n$ 个事件，则
$$P(\cup_{i=1}^nA_i)=\sum_{i=1}^nP(A_i)-\sum_{1\leqslant i < j \leqslant n}P(A_iA_j)+\sum_{1\leqslant i < j < k \leqslant n}P(A_iA_jA_k)-\cdots+(-1)^{n-1}P(A_1A_2\cdots A_n)$$
*** 条件概率
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
条件概率
**** Back
$P(A|B) = \frac{P(AB)}{P(B)}$
*** 乘法公式 :独立性:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
乘法公式
**** Back
$P(AB) = P(B)P(A|B)$
*** 全概率公式
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
全概率公式
**** Back
- 完备事件组 :: 样本空间的分割.
等价地，若每次试验的时候$\{B_i|i\in I\}$ 中至少有一个发生且只有一个发生，则$\{B_i|i\in I\}$ 是完备事件组.

- 定理（全概率公式） :: 设$\{B_i|i\in I\}$ 是一个完备事件组，并且对每个$i\in I$ 有$P(B_i)>0$ 对任意事件$A$ ，有$P(A)=\sum_{i\in I}P(B_i)P(A|B_i)$

- 全概率公式的意义 :: 导致结果$A$ 有各种原因（或条件）$B_1, B_2, \cdots$ ，在解决实际问题时，$P(A|B_i)$ 易知或易求，且已知$P(B_i)$ 时，可用全概率公式计算结果$A$发生的概率.
*** 贝叶斯公式
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
贝叶斯公式
**** Back
设$\{B_i|i\in I\}$ 是一个完备事件组且$P(B_i)>0$ ，$A$ 是一个事件且 $P(A)>0$ ，则
\[
P(B_i|A) = \frac{P(B_i)P(A|B_i)}{\sum_{j=1}^{n}P(B_j)P(A|B_j)}
\]

贝叶斯公式的意义：导致结果$A$ 有各种原因（或条件）$B_1, B_2, \cdots$ ，通过检验已知$A$ _已经发生_ ，再看各原因（或条件）发生的概率，可用 *贝叶斯公式*. 贝叶斯公式又称 *逆概率公式*.

+ 先验概率 :: $P(B_i)$ ，试验之前就知道的概率.
+ 后验概率 :: $P(B_i|A)$ ，试验过后知道的概率.
*** 相互独立 :独立性:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
相互独立
**** Back
设$A$ ，$B$ 是两事件，若 $P(AB)=P(A)P(B)$ ，则称事件$A$ 与事件$B$ 相互独立.
这些也相互独立：
 \[
\{\overline{A}, B\}, \{A, \overline{B}\}, \{\overline{A}, \overline{B}\}
\]
*** 伯努利概型
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
在 $n$ 重伯努利实验中事件 $A$ 恰好发生 $k$ 次的概率
**** Back
$$ \binom{n}{k}p^kp^{n-k} $$
** 概率分布 :概率分布:
*** 分布函数
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
分布函数
**** Back
$F(x) = P(X \le x), -\infty < x < \infty$

$P(a <X\le b) = P(X\le b) - P(X \le a) = F(b) - F(a)$
*** 概率密度函数
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
概率密度函数
**** Back
若$F(x)$ 是分布函数，如果存在定义在 $(-\infty, \infty)$ 上的非负实值函数$f(x)$ 使得
$$ F(x) = \int_{-\infty}^{x}f(y)\mathrm{d}y,\quad -\infty < x < \infty$$
则$f(x)$ 是 $X$ 的概率密度函数.
*** 随机变量函数分布 :随机变量函数分布:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
随机变量函数分布的积分转化法
**** Back
$g(x)$ 是（分段）连续或（分段）单调函数，如果对任何有界连续函数 $h(x)$ ，成立
\[
\int_{-\infty}^{+\infty}h[g(x)]f_X(x)\mathop{}\!\mathrm{d}x = \int_\alpha^\beta h(y)p(y)\mathop{}\!\mathrm{d}y
\]
其中 $-\infty\leqslant\alpha<\beta\leqslant+\infty$ ，则 $Y=g(X)$ 的概率密度为

\[
f_Y(y) = \left\{
\begin{array}{lc} \; p(y), & \alpha < y < \beta \\ \; 0,\mbox{其他} & \end{array} \right.
\]
二维随机变量函数分布与此类似.

** 常见分布 :常见分布:
*** 离散型
**** 二项分布 :二项分布:
***** 分布律
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
二项分布 $B(n, p)$ 的分布律
****** Back
$$ p_k = P(X = k) = \binom{n}{k}p^kp^{n-k} $$
***** 期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
二项分布的期望
****** Back
$np$
***** 方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
二项分布的方差
****** Back
$np(1-p)$
***** 二项分布的泊松逼近 :二项分布的近似:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
二项分布的泊松逼近
****** Back
若 $p$ 很小（$p \le 0.05$）、$n$ 较大（$n \ge 20$ ）时，近似计算公式：
$$b(k;n,p) = \binom{n}{k}p^kp^{n-k} \approx p(k;np) = \frac{(np)^k}{k!}e^{-np}$$
若 $p$ 很大，转换成 $b(n-k, n, 1-p)$
**** 泊松分布 :泊松分布:
***** 分布律
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
泊松分布 $\mathcal{P}(\lambda)$ 的分布律
****** Back
$p(k;\lambda) = \frac{\lambda^k}{k!}e^{-\lambda}, \quad k = 0, 1, 2, \cdots$
***** 期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
泊松分布的期望
****** Back
$\lambda$
***** 方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
泊松分布的方差
****** Back
$\lambda$
*** 连续型
**** 均匀分布 :均匀分布:
***** 概率密度函数
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
均匀分布 $U(a,b)$ 的概率密度函数
****** Back
$f(x)=\frac{1}{b - a}I_{[a, b]}(x)$
***** 期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
均匀分布的期望
****** Back
$\frac{a + b}{2}$
***** 方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
均匀分布的方差
****** Back
$\frac{(b-a)^2}{12}$
**** 正态分布 :正态分布:
***** 概率密度函数
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
正态分布概率密度函数
****** Back
$f(x) = \frac{1}{\sqrt{2\pi}\sigma}e^{-\frac{1}{2\sigma^2}(x-\mu)^2}, -\infty < x < \infty$
***** 期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
正态分布的期望
****** Back
$\mu$
***** 方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
正态分布的方差
****** Back
$\sigma^2$
***** 正态概率计算公式 :计算概率:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
正态概率计算公式
****** Back
$\varPhi(x)$ 是标准正态分布函数.
$$ P(a < X \le b) = \varPhi(\frac{b - \mu}{\sigma}) - \varPhi(\frac{a - \mu}{\sigma}) $$
***** 怎么算 $\int_{-\infty}^{\infty}e^{-\frac{1}{2}x^2}\mathrm{d}x$
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
$\int_{-\infty}^{\infty}e^{-\frac{1}{2}}\mathrm{d}x$
****** Back
用这个算：
$\int_{-\infty}^{\infty}\frac{1}{2\pi}e^{-\frac{1}{2}x^2}\mathrm{d}x = 1$
**** 指数分布 :指数分布:
***** 概率密度函数
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
指数分布 $\mathcal{E}(\lambda)$ 的概率密度函数
****** Back
$f(x) = \lambda e^{-\lambda x}$
***** 期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
指数分布的期望
****** Back
$\frac{1}{\lambda}$
***** 方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
指数分布的方差
****** Back
$\frac{1}{\lambda^2}$
** 多维随机变量
*** n 维随机变量
**** 若干个随机变量的最大值的分布 :分布函数:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
若干个随机变量的最 *大* 值的分布
***** Back
相互独立的随机变量 $X_1, \cdots, X_n$ ，$X_i$ 的分布函数为$F_{X_i}(x), i = 1, \cdots, n$
$$F_{\mbox{max}}(x) = \prod_{i = 1}^n F_{X_i}(x)$$
**** 若干个随机变量的最小值的分布 :分布函数:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
若干个随机变量的最 *小* 值的分布
***** Back
相互独立的随机变量 $X_1, \cdots, X_n$ ，$X_i$ 的分布函数为$F_{X_i}(x), i = 1, \cdots, n$
$$F_{\mbox{min}}(x) = 1 - \prod_{i = 1}^n (1 - F_{X_i}(x))$$
*** 二维随机变量 :随机变量函数分布:
**** 和的分布
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
和的分布 (卷积公式)
***** Back
$X$ 与 $Y$ 相互独立，$Z = X + Y$
$$ f_Z(z) = \int_{-\infty}^{\infty}f_X(x)f_Y(z-x)\mathrm{d}x $$
**** 商的分布
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
商的分布
***** Back
$X$ 与 $Y$ 相互独立，$Z = \frac{X}{Y}$
$$ f_Z(z) = \int_{-\infty}^{\infty}|y|f(zy,y)\mathrm{d}y$$
** 多维随机变量的数字特征
*** 期望 :期望:
**** 离散型随机变量的期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
离散型随机变量的期望
***** Back
$$E(X) = \sum_{k \ge 1}x_kp_k$$
**** 连续型随机变量的期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
连续型随机变量的期望
***** Back
$$ E(x) = \int_{-\infty}^{\infty}xf(x)\mathrm{d}x $$
若 $\int_{-\infty}^{\infty}|x|f(x)\mathrm{d}x = \infty$ 则不存在.
**** 连续型随机变量函数的期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
连续型随机变量函数的期望
***** Back
$$ E(g(x)) = \int_{-\infty}^{\infty}g(x)f(x)\mathrm{d}x $$
**** 期望的性质
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
期望的性质
***** Back
1. 线性性
2. 单调性
3. 若 *相互独立* ，则乘积的期望等于期望的乘积.
4. 收缩性 $|E(x)| \le E(|X|)$
5. 马尔可夫不等式
6. 若 $E(|X|) = 0$ ,则$P(X=0) = 1$.
**** 马尔可夫不等式
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
马尔可夫不等式
***** Back
设$X$ 是数学期望存在的随机变量，则对任何 $c>0$
$$ P(|X|\ge c) \le \frac{E(|X|)}{c} $$
*** 方差 :方差:
**** 方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
方差
***** Back
$D(X) = E\left((X - E(X))^2\right)$
标准差（均方差）为
$$ \sigma_X = \sqrt{D(X)} $$
**** 方差的计算公式
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
方差的计算公式
***** Back
$$D(X) = E(X^2) - \left(E(X)\right)^2$$
**** 方差的性质
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
方差的性质
***** Back
1. $D(c) = 0$
2. $D(kX) = k^2D(X)$
3. 对任意常数$C$ ，  $D(X) \le E((X-C)^2)$
4. *相互独立* 则和的方差等于方差的和.
**** 切比雪夫不等式
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
切比雪夫不等式
***** Back
对任意随机变量$X$ ，若$D(X)$ 存在，则对任意$\varepsilon > 0$ ，有
$$P(|X-E(X)|\ge \varepsilon) \le \frac{D(X)}{\varepsilon^2}$$
*** 协方差和相关系数 :协方差:相关系数:
**** 协方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
协方差
***** Back
$\operatorname{Cov}(X, Y) = E\left((X-E(X)(Y-E(Y))\right)$
$$D(X+Y) = D(X) + D(Y) + 2\operatorname{Cov}(X,Y) $$
**** 协方差计算公式
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
协方差计算公式
***** Back
$$\operatorname{Cov}(X, Y) = E(XY) - E(X)E(Y)$$
**** 协方差的性质
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
协方差的性质
***** Back
1. 对称性： $\operatorname{Cov}(X,Y) = \operatorname{Cov}(Y,X)$
2. 若 $a,b$ 为常数，则
   $$ \operatorname{Cov}(aX, bY) = ab\operatorname{Cov}(X, Y) $$
3.  $$\operatorname{Cov}(X_1 + X_2, Y) = \operatorname{Cov}(X_1, Y) + \operatorname{Cov}(X_2, Y)$$
**** 相关系数
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
相关系数
***** Back
$$\rho = \rho_{XY} = \frac{\operatorname{Cov}(X,Y)}{\sqrt{D(X)}{\sqrt{D(Y)}}}$$
**** 相关系数的意义
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
相关系数的意义
***** Back
1. $|\rho| = 1$ 的充分必要条件是$X$ 与$Y$ 之间线性相关，即存在常数$a, b$ ，使得
   $$ P(Y = aX + b) = 1 $$
2. $\rho = 0$ 则不相关，不能推出独立性，但是二维正态分布可以推出独立性.
** 概率极限定理
*** 中心极限定理 :中心极限定理:
**** 莱维-林德伯格中心极限定理
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
莱维-林德伯格中心极限定理
***** Back
独立同分布随机变量序列 $\{X_n\}$ ，$E(X)=\mu$ ， $D(X_n) = \sigma^2 > 0$ ，则随机变量
$$ \frac{1}{\sqrt{n}\sigma}\left(\sum_{k = 1}^{n}X_k - n\mu\right)$$
的分布函数收敛到标准正态分布函数 $\varPhi(x)$.
**** 棣莫弗-拉普拉斯中心极限定理 :二项分布的近似:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
棣莫弗-拉普拉斯中心极限定理
***** Back
设$n_A$ 为$n$ 重伯努利试验中事件$A$ 出现的次数，又每次试验中$A$ 发生的概率为$p$，则
$$ \frac{n_A - np}{\sqrt{np(1-p)}} $$
的分布函数收敛到标准正态分布函数 $\varPhi(x)$.

当$p$ 很接近 0 或 1 时用正态分布近似二项分布要求$n$ 相当大，否则不如泊松近似.
** 统计量 :统计量:
*** 样本平均值
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
样本平均值
**** Back
$$\overline{X} = \frac{1}{n}\sum_{i = 1}^{n}X_i$$
*** 样本方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
样本方差
**** Back
$$S^2 = \frac{1}{n - 1}\sum_{i = 1}^n(X_i - \overline{X})^2$$
*** 样本平均值的期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
样本平均值的期望
**** Back
$$E(\overline{X}) = \mu$$
*** 样本平均值的方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
样本平均值的方差
**** Back
$$D(\overline{X}) = \frac{\sigma^2}{n}$$
*** 样本方差的期望
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
样本方差的期望
**** Back
$$E(S^2) = \sigma^2$$
** 抽样分布 :抽样分布:
*** $\chi^2$ 分布
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
$\chi^2$ 分布
**** Back
$X_i(i = 1, 2, \cdots, n)$ 相互独立且服从标准正态分布，自由度为 $n$ 的$\chi^2 分布$ :
$$\chi^2  = X_1^2 + X_2^2 + \cdots + X_n^2$$
记为 $\chi^2 \sim \chi^2 (n)$.
*** $\chi^2$ 均值和方差
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
$E(\chi^2)$ $D(\chi^2)$
**** Back
$E(X_i) = 0$

$D(X_i) = 1 = E(X_i^2) - (E(X_i^2))^2$

$E(X_i^2) = 1 + 0 = 1$,
$E(X_i^4) = 3$

$D(X_i^2) = E(X_i^4) - (E(X_i^2))^2 = 3 - 1^2 = 2$

$$E(\chi^2) = n$$
$$D(\chi^2) = 2n$$

*** $t$ 分布
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
$t$ 分布
**** Back
随机变量 $X\sim N(0, 1), Y\sim \chi^2(n)$ ，自由度为 $n$ 的$t$ 分布:
$$T = \frac{X}{\sqrt{Y/n}}$$
记为 $T \sim t (n)$.
*** $t$ 分布的上分位点结论
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
$t$ 分布的上分位点结论
**** Back
$t_{1 - a}(n) = -t_a(n)$
*** $F$ 分布
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
$F$ 分布
**** Back
随机变量 $X\sim \chi^2(n_1), Y\sim \chi^2(n_2)$ ，自由度为 $n_1, n_2$ 的$F$ 分布:
$$F = \frac{X/n_1}{Y/n_2}$$
记为 $F \sim F(n_1, n_2)$.
*** $F$ 分布的结论
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
$F$ 分布的结论
**** Back
1. 若 $F \sim F(n_1, n_2)$ ，则$\frac{1}{F}\sim F(n_2, n_1)$
2. 若 $T\sim t(n)$ ，则$T^2 \sim F(1, n)$
3. $F(n_1, n_2)$ 分布的数学期望是 $\frac{n_2}{n_2 - 2}$
*** 正态总体基本定理 :正态分布:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
正态总体基本定理
**** Back
1. $\frac{\overline{X} - \mu}{\sigma/\sqrt{n}}\sim N(0, 1)$
2. $\frac{(n-1)S^2}{\sigma^2}\sim\chi^2(n-1)$
3. $\overline{X}$ 与 $S^2$ 相互独立.
4. $\frac{\overline{X} - \mu}{S/\sqrt{n}}\sim t(n - 1)$
** 正态分布区间估计 :区间估计:
*假设检验* 和这个类似.
*** 单个
**** 均值
***** 方差已知
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
区间估计$\mu$ 单个正态\(N(\mu, \sigma^2)\)，已知$\sigma$
****** Back
枢轴量：
$$\frac{\overline{X} - \mu}{\sigma/\sqrt{n}}\sim N(0, 1)$$
$\mu$ 的置信度为 $1-\alpha$ 的置信区间为

$$\left(\overline{X} \pm \frac{\sigma}{\sqrt{n}}z_{\frac{\alpha}{2}}\right)$$
***** 方差未知
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
区间估计$\mu$ 单个正态\(N(\mu, \sigma^2)\)，$\sigma$ 未知
****** Back
枢轴量：
$$\frac{\overline{X} - \mu}{S/\sqrt{n}}\sim t(n - 1)$$
$\mu$ 的置信度为 $1-\alpha$ 的置信区间为
$$\left(\overline{X} \pm \frac{S}{\sqrt{n}}t_{\frac{\alpha}{2}}(n-1) \right)$$
**** 方差
***** 均值未知
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
区间估计$\sigma$ 单个正态\(N(\mu, \sigma^2)\)，$\mu$ 未知
****** Back
枢轴量：
$$\frac{(n-1)S^2}{\sigma^2}\sim\chi^2(n-1)$$
$\sigma$ 的置信度为 $1-\alpha$ 的置信区间为
$$\left(\sqrt{\frac{(n-1)S^2}{\chi^2_{\frac{\alpha}{2}}(n-1)}}, \sqrt{\frac{(n-1)S^2}{\chi^2_{1 - \frac{\alpha}{2}}(n-1)}}\right)$$
*** 多个
**** 均值
***** 方差已知
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
区间估计$\mu_1 - \mu_2$ 两正态\(N(\mu_1, \sigma_1^2), N(\mu_2, \sigma_2^2)\)，$\sigma_1, \sigma_2$ 已知
****** Back
枢轴量：
$$ \frac{(\overline{X} - \overline{Y}) - (\mu_1 - \mu_2)}{\sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_1^2}{n_1}}} \sim N(0, 1) $$
$\mu_1 - \mu_2$ 的置信度为 $1-\alpha$ 的置信区间为
$$\left(\overline{X} - \overline{Y} \pm z_{\frac{\alpha}{2}}\sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_1^2}{n_1}} \right)$$
***** 方差相等但未知
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
区间估计$\mu_1 - \mu_2$ 两正态\(N(\mu_1, \sigma_1^2), N(\mu_2, \sigma_2^2)\)，$\sigma_1 = \sigma_2 = \sigma$ 未知
****** Back
枢轴量：
$$ \frac{(\overline{X} - \overline{Y}) - (\mu_1 - \mu_2)}{S_w\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}} \sim t(n_1 + n_2 - 2) $$
$\mu_1 - \mu_2$ 的置信度为 $1-\alpha$ 的置信区间为
$$\left(\overline{X} - \overline{Y} \pm S_w \sqrt{\frac{1}{n_1}+\frac{1}{n_2}}t_{\frac{\alpha}{2}}(n_1 + n_2 - 2)\right)$$
$S_w^2 = \frac{(n_1 - 1)S_1^2 + (n_2 - 1)S_2^2}{n_1 + n_2 - 2}$
**** 方差
***** 均值未知
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
区间估计$\sigma_1^2/\sigma_2^2$ 两正态\(N(\mu_1, \sigma_1^2), N(\mu_2, \sigma_2^2)\)，$\mu_1,\mu_2$ 未知
****** Back
枢轴量：
$$\frac{S_1^2/S_2^2}{\sigma_1^2/\sigma_2^2} = \frac{\frac{(n_1 - 1)S_1^2}{\sigma_1^2}/(n_1-1)}{\frac{(n_2 - 1)S_2^2}{\sigma_2^2}/(n_2-1)} \sim F(n_1 - 1, n_2 - 1)$$
$\sigma_1^2/\sigma_2^2$ 的置信度为 $1-\alpha$ 的置信区间为
$$\left(\frac{S_1^2/S_2^2}{F_{\frac{\alpha}{2}}(n_1 - 1, n_2 - 1)}, \frac{S_1^2/S_2^2}{F_{1 - \frac{\alpha}{2}}(n_1 - 1, n_2 - 1)}\right)$$
