// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat May 27 10:06:49 2017

low_pass_filter1 low_pass_filter1_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.ast_sink_data(ast_sink_data_sig) ,	// input [7:0] ast_sink_data_sig
	.ast_sink_valid(ast_sink_valid_sig) ,	// input  ast_sink_valid_sig
	.ast_source_ready(ast_source_ready_sig) ,	// input  ast_source_ready_sig
	.ast_sink_error(ast_sink_error_sig) ,	// input [1:0] ast_sink_error_sig
	.ast_source_data(ast_source_data_sig) ,	// output [22:0] ast_source_data_sig
	.ast_sink_ready(ast_sink_ready_sig) ,	// output  ast_sink_ready_sig
	.ast_source_valid(ast_source_valid_sig) ,	// output  ast_source_valid_sig
	.ast_source_error(ast_source_error_sig) 	// output [1:0] ast_source_error_sig
);

