// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun May 14 10:10:14 2017

AD_Data AD_Data_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.AD_DigData_In(AD_DigData_In_sig) ,	// input  AD_DigData_In_sig
	.AD_CSn(AD_CSn_sig) ,	// output  AD_CSn_sig
	.AD_Clk(AD_Clk_sig) ,	// output  AD_Clk_sig
	.AD_Address(AD_Address_sig) ,	// output  AD_Address_sig
	.Data_Out(Data_Out_sig) ,	// output [9:0] Data_Out_sig
	.CS_Valid_Sig(CS_Valid_Sig_sig) 	// output  CS_Valid_Sig_sig
);

