// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun May 14 10:10:39 2017

Digitron_NumDisplay Digitron_NumDisplay_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.Data(Data_sig) ,	// input [9:0] Data_sig
	.Digitron_Out(Digitron_Out_sig) ,	// output [7:0] Digitron_Out_sig
	.DigitronCS_Out(DigitronCS_Out_sig) 	// output [5:0] DigitronCS_Out_sig
);

defparam Digitron_NumDisplay_inst.T100MS = 'b0000000011001000;
defparam Digitron_NumDisplay_inst._0 = 'b11000000;
defparam Digitron_NumDisplay_inst._1 = 'b11111001;
defparam Digitron_NumDisplay_inst._2 = 'b10100100;
defparam Digitron_NumDisplay_inst._3 = 'b10110000;
defparam Digitron_NumDisplay_inst._4 = 'b10011001;
defparam Digitron_NumDisplay_inst._5 = 'b10010010;
defparam Digitron_NumDisplay_inst._6 = 'b10000010;
defparam Digitron_NumDisplay_inst._7 = 'b11111000;
defparam Digitron_NumDisplay_inst._8 = 'b10000000;
defparam Digitron_NumDisplay_inst._9 = 'b10010000;
defparam Digitron_NumDisplay_inst._A = 'b10001000;
defparam Digitron_NumDisplay_inst._B = 'b10000011;
defparam Digitron_NumDisplay_inst._C = 'b11000110;
defparam Digitron_NumDisplay_inst._D = 'b10100001;
defparam Digitron_NumDisplay_inst._E = 'b10000110;
defparam Digitron_NumDisplay_inst._F = 'b10001110;
