// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Sat Apr 08 20:58:39 2017

Buzzer_module Buzzer_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.SecL(SecL_sig) ,	// input [3:0] SecL_sig
	.SecH(SecH_sig) ,	// input [3:0] SecH_sig
	.MinL(MinL_sig) ,	// input [3:0] MinL_sig
	.MinH(MinH_sig) ,	// input [3:0] MinH_sig
	.Buzzer_Out(Buzzer_Out_sig) 	// output  Buzzer_Out_sig
);

defparam Buzzer_module_inst.Di = 'b1100001101010000;
defparam Buzzer_module_inst.Da = 'b110000110101000;
