// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Sat Apr 08 20:58:43 2017

Digitron_TimeDisplay_module Digitron_TimeDisplay_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.DispWeek(DispWeek_sig) ,	// input  DispWeek_sig
	.AdjtWeek_n(AdjtWeek_n_sig) ,	// input  AdjtWeek_n_sig
	.Digitron_Out(Digitron_Out_sig) ,	// output [7:0] Digitron_Out_sig
	.DigitronCS_Out(DigitronCS_Out_sig) ,	// output [5:0] DigitronCS_Out_sig
	.SecL(SecL_sig) ,	// input [3:0] SecL_sig
	.SecH(SecH_sig) ,	// input [3:0] SecH_sig
	.MinL(MinL_sig) ,	// input [3:0] MinL_sig
	.MinH(MinH_sig) ,	// input [3:0] MinH_sig
	.HourL(HourL_sig) ,	// input [3:0] HourL_sig
	.HourH(HourH_sig) ,	// input [3:0] HourH_sig
	.Week(Week_sig) 	// input [3:0] Week_sig
);

defparam Digitron_TimeDisplay_module_inst.T100MS = 'b0000000011001000;
defparam Digitron_TimeDisplay_module_inst._0 = 'b00111111;
defparam Digitron_TimeDisplay_module_inst._1 = 'b00000110;
defparam Digitron_TimeDisplay_module_inst._2 = 'b01011011;
defparam Digitron_TimeDisplay_module_inst._3 = 'b01001111;
defparam Digitron_TimeDisplay_module_inst._4 = 'b01100110;
defparam Digitron_TimeDisplay_module_inst._5 = 'b01101101;
defparam Digitron_TimeDisplay_module_inst._6 = 'b01111101;
defparam Digitron_TimeDisplay_module_inst._7 = 'b00000111;
defparam Digitron_TimeDisplay_module_inst._8 = 'b01111111;
defparam Digitron_TimeDisplay_module_inst._9 = 'b01101111;
