// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat Apr 15 15:51:18 2017

detect_module detect_module_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.RX_Pin_In(RX_Pin_In_sig) ,	// input  RX_Pin_In_sig
	.neg_sig(neg_sig_sig) 	// output  neg_sig_sig
);

