<title>表情符号</title>
<script language="Javascript">
<!-- hide

function insertsmilie(smilieface){

	window.opener.document.frmAnnounce.body.value+=smilieface;
}
// -->
</script>

<table border="0" width="95%" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td>
<table border="0" width="100%" cellspacing="1" cellpadding="4">
  <tr>
    <td><a name="smilies"></a><b>Smilies</b></td>
  </tr>
  <tr>
    <td">
    <p>
    在本论坛中你可以使用一些网络中常用的表情符号，论坛可以将他自动转换成相关的图标，比如一个笑脸
    <img border="0" src="pic/icon_smile.gif">或者一个不赞成的图标 
    <img border="0" src="pic/icon_smile_sad.gif">. 在这里你可以直接点击图标就可以在发言栏里面自动显示相关的表情符号，或者你记住一些常用的表情符号代码也可以在里面直接用了，一般用法都是在表情的两头加上[]就可以了，下面列出了本论坛支持的表情符号 :<br>
    <table border="0" align="center" cellpadding="5">
      <tr valign="top">
        <td>
        <table border="0" align="center">
          <tr>
            <td><a href="Javascript:insertsmilie('[:)]');"><img border="0" hspace="10" src="pic/icon_smile.gif"></a></td>
            <td">心情好好哦</td>
            <td">[:)]</td>
          </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[:D]');"><img alt border="0" hspace="10" src="pic/icon_smile_big.gif"></a></td>
            <td>大笑~</td>
            <td>[:D]</td>
          </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[8D]');"><img alt border="0" hspace="10" src="pic/icon_smile_cool.gif"></a></td>
            <td>cool毖了哦</td>
            <td>[8D]</td>
          </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[:I]');"><img alt border="0" hspace="10" src="pic/icon_smile_blush.gif"></a></td>
            <td>羞死了</td>
            <td>[:I]</td>
          </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[:p]');"><img alt border="0" hspace="10" src="pic/icon_smile_tongue.gif"></a></td>
            <td>嘻嘻，不好意思</td>
            <td>[:P]</td>
         </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[}:)]');"><img alt border="0" hspace="10" src="pic/icon_smile_evil.gif"></a></td>
            <td>嘿嘿，我是大魔头</td>
            <td>[}:)]</td>
          </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[;)]');"><img alt border="0" hspace="10" src="pic/icon_smile_wink.gif"></a></td>
            <td>知道我要做什么吗</td>
            <td>[;)]</td>
          </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[:o)]');"><img alt border="0" hspace="10" src="pic/icon_smile_clown.gif"></a></td>
            <td>小丑</td>
            <td>[:o)]</td>
          </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[B)]');"><img alt border="0" hspace="10" src="pic/icon_smile_blackeye.gif"></a></td>
            <td>一个晚上没有睡啊</td>
            <td>[B)]</td>
          </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[8]');"><img alt border="0" hspace="10" src="pic/icon_smile_8ball.gif"></a></td>
            <td>8号球</td>
            <td>[8]</td>
          </tr>
        </table>
        </td>
        <td>
        <table border="0" align="center">
            <tr>
              <td><a href="Javascript:insertsmilie('[:(]');"><img alt border="0" hspace="10" src="pic/icon_smile_sad.gif"></a></td>
              <td>坚决反对！</td>
              <td>[:(]</td>
            </tr>
            <tr>
              <td><a href="Javascript:insertsmilie('[8)]');"><img alt border="0" hspace="10" src="pic/icon_smile_shy.gif"></a></td>
              <td>羞死了</td>
              <td>[8)]</td>
            </tr>
            <tr>
              <td><a href="Javascript:insertsmilie('[:0]');"><img alt border="0" hspace="10" src="pic/icon_smile_shock.gif"></a></td>
              <td>不要吧~</td>
              <td>[:O]</td>
            </tr>
            <tr>
              <td><a href="Javascript:insertsmilie('[:(!]');"><img alt border="0" hspace="10" src="pic/icon_smile_angry.gif"></a></td>
              <td>气死我了</td>
              <td>[:(!]</td>
            </tr>
            <tr>
              <td><a href="Javascript:insertsmilie('[xx(]');"><img alt border="0" hspace="10" src="pic/icon_smile_dead.gif"></a></td>
              <td>死掉了、死掉了。</td>
              <td>[xx(]</td>
            </tr>
            <tr>
              <td><a href="Javascript:insertsmilie('[|)]');"><img alt border="0" hspace="10" src="pic/icon_smile_sleepy.gif"></a></td>
              <td>休息一下</td>
              <td>[|)]</td>
            </tr>
            <tr>
              <td><a href="Javascript:insertsmilie('[:X]');"><img alt border="0" hspace="10" src="pic/icon_smile_kisses.gif"></a></td>
              <td>给你一个kiss</td>
              <td>[:X]</td>
            </tr>
            <tr>
              <td><a href="Javascript:insertsmilie('[^]');"><img alt border="0" hspace="10" src="pic/icon_smile_approve.gif"></a></td>
              <td>我赞成</td>
              <td>[^]</td>
           </tr>
            <tr>
              <td><a href="Javascript:insertsmilie('[V]');"><img alt border="0" hspace="10" src="pic/icon_smile_dissapprove.gif"></a></td>
              <td>不同意！</td>
              <td>[V]</td>
           </tr>
          <tr>
            <td><a href="Javascript:insertsmilie('[?]');"><img alt border="0" hspace="10" src="pic/icon_smile_question.gif"></a></td>
            <td>有个问题哦</td>
            <td>[?]</td>
          </tr>
        </table>
        </td>
      </tr>
    </table></p>
    </td>
  </tr>
</table>
    </td>
  </tr>
</table>

