// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Sat Apr 08 17:10:21 2017

Sel_module Sel_module_inst
(
	.RSTn(RSTn_sig) ,	// input  RSTn_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Start(Start_sig) ,	// input  Start_sig
	.K1(K1_sig) ,	// input  K1_sig
	.K2(K2_sig) ,	// input  K2_sig
	.K3(K3_sig) ,	// input  K3_sig
	.K4(K4_sig) ,	// input  K4_sig
	.LED_Out(LED_Out_sig) ,	// output [3:0] LED_Out_sig
	.Player_Number(Player_Number_sig) ,	// output [3:0] Player_Number_sig
	.Buzzer_Answer(Buzzer_Answer_sig) ,	// output  Buzzer_Answer_sig
	.Timer_Start(Timer_Start_sig) 	// output  Timer_Start_sig
);

